version: 2

sources:
  - name: churn
    database: churn
    schema: public
    description: '{ { doc("churn_source") } }'
    tables:
      - name: population
        description: '{ { doc("population_table") } }'
        columns:
          - name: zipcode
            description: '{ { doc("zipcode_col") } }'
            tests:
              - unique
              - not_null
          - name: population
            description: '{ { doc("population_col") } }'
      - name: customer_details
        description: '{ { doc("customer_table") } }'

models:
  - name: stg_churn__population
    description: '{{ doc("population_table") }}'
    columns:
      - name: zipcode
        description: '{ { doc("zipcode_col") } }'
        tests:
          - unique
          - not_null
  - name: stg_churn__customer_details
    description: '{ { doc("customer_table") } }'