dbtdvdrental:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: "{{ env_var('DBT_POSTGES_DB') }}"
      schema: "{{ env_var('DBT_DBT_SCHEMA') }}"

  target: dev
