transformations:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: aditya
      pass: aditya1234
      dbname: churn
      schema: public
  target: dev
